INSERT INTO SOURCE_DATA (id, num) VALUES (1, 1);
INSERT INTO SOURCE_DATA (id, num) VALUES (2, 2);
INSERT INTO SOURCE_DATA (id, num) VALUES (3, 3);
INSERT INTO SOURCE_DATA (id, num) VALUES (4, 3);
INSERT INTO SOURCE_DATA (id, num) VALUES (5, 10);
INSERT INTO SOURCE_DATA (id, num) VALUES (6, 12);
